server:
  port: 8080

spring:
  datasource:
    username: root
    password: ZCzc3737
    url: jdbc:mysql://localhost:3306/horizon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

    job-store-type: jdbc

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.markz.horizon.entity.dao